# Meta Data for SEO

## Homepage
title = "ctv.lab"
titleSeparator = "-"
titleAddition = "laboratório de comunicação"
description = "Criamos soluções para projetos preocupados com a transformação social."

## Open Graph + Twitter Cards
images = ["ctvlab.png"]
twitterSite = "ctv_lab"
twitterCreator = "ctv_lab"
facebookAuthor = "ctv.lab"
facebookPublisher = "ctv.lab"
ogLocale = "pt_BR"

## JSON-LD
schemaType = "Organization"
schemaLogo = "ctvlab.png"
schemaTwitter = "https://twitter.com/ctv_lab"
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Criado por <a href=\"https://github.com/fakegermano/\">fakegermano</a>, empoderado por <a href=\"https://gohugo.io/\">Hugo</a> e <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = ""

# Edit Page
docsRepo = ""
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
